export const FETCH_USER = 'FETCH_USER';

export const OPEN_SIGN_UP_MODAL = 'OPEN_SIGN_UP_MODAL';
export const CLOSE_SIGN_UP_MODAL = 'CLOSE_SIGN_UP_MODAL';

export const ALREADY_SUBSCRIBED = 'ALREADY_SUBSCRIBED';
export const SUCCESSFUL_SUBSCRIPTION = 'SUBSCRIPTION_SUCCESFUL';
export const WAIT_SUBSCRIPTION = 'WAIT_SUBSCRIPTION';
export const REPORT_ERROR_SUBSCRIPTION = 'REPORT_ERROR_SUBSCRIPTION';
export const NOT_SUBSCRIBED = 'NOT_SUBSCRIBED';